#!/usr/bin/env python3

# example launcher for DisplayCluster
# this should work for most cases, but can be modified for a particular
# installation if necessary

import os
import sys
import json
import subprocess
import distutils.spawn
import signal
import shlex

def signalhandler(signum, a):
    print( "signalhandler")
    os.system("kill -- -%s" % os.getpid())
    sys.exit(1)

signal.signal(signal.SIGINT, signalhandler)

if 'DISPLAYCLUSTER_SIF' not in os.environ:
    print("DISPLAYCLUSTER_SIF not set")
    sys.exit(1)

if 'DISPLAYCLUSTER_DIR' not in os.environ:
    os.environ['DISPLAYCLUSTER_DIR'] = os.path.dirname(os.path.abspath(__file__))

if 'DISPLAYCLUSTER_INSTALL' not in os.environ:
    os.environ['DISPLAYCLUSTER_INSTALL'] = '/usr/local'
    
if 'DISPLAYCLUSTER_TIMEOUT' not in os.environ:
    os.environ['DISPLAYCLUSTER_TIMEOUT'] = '5'

dcPath = os.environ['DISPLAYCLUSTER_DIR']
sif = os.environ['DISPLAYCLUSTER_SIF']

if 'DISPLAYCLUSTER_EXEC' not in os.environ:
    os.environ['DISPLAYCLUSTER_EXEC'] = 'displaycluster'

if 'DISPLAYCLUSTER_PYTHONPORT' not in os.environ:
    os.environ['DISPLAYCLUSTER_PYTHONPORT'] = '1910'

if 'DISPLAYCLUSTER_NETWORKPORT' not in os.environ:
    os.environ['DISPLAYCLUSTER_NETWORKPORT'] = '1701'

if 'DISPLAYCLUSTER_LOG_THRESHOLD' not in os.environ:
    os.environ['DISPLAYCLUSTER_LOG_THRESHOLD'] = '4'

if 'LD_LIBRARY_PATH' in os.environ:
	os.environ['LD_LIBRARY_PATH'] = os.environ['LD_LIBRARY_PATH'] + ':/usr/local/lib'
else:
	os.environ['LD_LIBRARY_PATH'] = '/usr/local/lib'

if 'DISPLAYCLUSTER_CONFIG' not in os.environ:
    os.environ['DISPLAYCLUSTER_CONFIG'] = dcPath + '/configuration.json'

if 'DISPLAYCLUSTER_MPIARGS' not in os.environ:
    os.environ['DISPLAYCLUSTER_MPIARGS'] = ' '

# set the Python path so the pydc module can be found
if 'PYTHONPATH' not in os.environ:
    os.environ['PYTHONPATH'] = dcPath + '/python'
else:
    os.environ['PYTHONPATH'] += os.pathsep + dcPath + '/python'

# for example scripts
os.environ['PYTHONPATH'] += os.pathsep + dcPath + '/examples'

# add in the default Python path provided by the Python interpreter since it
# is not provided in our GUI Python console
os.environ['PYTHONPATH'] += os.pathsep + os.pathsep.join(sys.path)

# form the MPI host list

# rank 0 is always on localhost
hostList = ['localhost']

# configuration.json gives the rest of the hosts
try:
    configPath = os.environ.get('DISPLAYCLUSTER_CONFIG', dcPath + '/configuration.json')

    with open(configPath) as f:
        config = json.load(f)

    for process in config['processes']:
        host = process.get('host')

        if host is None:
            print( 'Error, no "host" key in process entry.')
            exit(-1)

        hostList.append(host)
except:
    print( 'Error processing configuration.json. Make sure you have created a configuration.json and put it in ' + dcPath + '/. An example is provided in the examples/ directory.')
    exit(-2)

hostListString = ",".join(hostList)
print((hostListString))

# find full path to mpirun; if MPI is installed in a non-standard location the
# full path may be necessary to launch correctly across the cluster.
mpirunCommand = distutils.spawn.find_executable('mpirun')

if mpirunCommand is None:
    print( 'Error, could not find mpirun executable in PATH')
    exit(-3)

startCommand = mpirunCommand + ' -host ' + hostListString + ' ' + os.environ['DISPLAYCLUSTER_MPIARGS']
startCommand = startCommand + ' -x LD_LIBRARY_PATH -x DISPLAYCLUSTER_TIMEOUT -x DISPLAYCLUSTER_INSTALL'
startCommand = startCommand + ' -x DISPLAYCLUSTER_EXEC -x DISPLAYCLUSTER_DIR -x DISPLAYCLUSTER_CONFIG '
startCommand = startCommand + ' -x DISPLAYCLUSTER_LOG_THRESHOLD -x PYTHONPATH -x DISPLAYCLUSTER_SCREENSAVER_IMAGE'
startCommand = startCommand + ' -x DISPLAYCLUSTER_PYTHONPORT -x DISPLAYCLUSTER_NETWORKPORT'
startCommand = startCommand + ' apptainer run --nv  ' + sif
startCommand = startCommand + ' sh %s/bin/displaycluster.sh %s/bin/displaycluster.py' % (os.environ['DISPLAYCLUSTER_INSTALL'], os.environ['DISPLAYCLUSTER_INSTALL'])

print( 'launching with command: ' + startCommand)

subprocess.call(shlex.split(startCommand))
os.system("kill -- -%s" % os.getpid())
